"""
dm/image_event_handler.py — Automatic image generation trigger logic.

Evaluates whether a narrative event deserves an image, then generates
and delivers it via Telegram.

Usage:
    from dm.image_event_handler import ImageEventHandler, ImageContext
    from dm.image_provider import get_provider

    provider = get_provider("pollinations")
    handler = ImageEventHandler(provider=provider)
    image_path = await handler.maybe_generate(context)
"""
import time
from dataclasses import dataclass, field
from typing import Any

from dm.image_provider import (
    ImageGenerationError,
    ImageProvider,
    ImageResult,
    build_scene_prompt,
)

# ── Default triggers ────────────────────────────────────────────────────────────

DEFAULT_AUTO_IMAGE_TRIGGERS: dict[str, bool] = {
    "nat_20": True,
    "nat_1": True,
    "player_death": True,
    "npc_death": True,
    "boss_intro": True,
    "boss_death": True,
    "session_start": True,
    "session_end": True,
    "discovery": True,
    "critical_wound": True,
    "dramatic_victory": True,
    "normal_turn": False,
    "other": False,
}


# ── ImageContext ────────────────────────────────────────────────────────────────

@dataclass
class ImageContext:
    """
    Everything the event handler needs to decide + generate an image.
    """
    scene_type: str           # "nat_20", "boss_death", "discovery", etc.
    narrative: str            # The narrative text generated by the DM
    genre: str = "fantasy"    # Campaign genre for style guidance
    characters: list[str] = field(default_factory=list)  # Names in scene
    mood: str = "dramatic"    # "dark", "epic", "tense", "tender"
    combat_state: bool = False
    is_boss_combat: bool = False
    player_hp_percent: float = 1.0  # 0.0 to 1.0
    damage_dealt: int = 0
    is_critical: bool = False
    is_fumble: bool = False
    npc_killed: str | None = None  # Name of NPC that died
    player_who_died: str | None = None
    location_name: str | None = None
    metadata: dict = field(default_factory=dict)


# ── ImageEventHandler ──────────────────────────────────────────────────────────

class ImageEventHandler:
    """
    Decides automatically when to generate scene images and orchestrates
    the generation + delivery pipeline.

    Thread-safe: uses timestamps for cooldown tracking.
    """

    def __init__(
        self,
        provider: ImageProvider,
        triggers: dict[str, bool] | None = None,
        cooldown_seconds: float = 15.0,
        max_per_combat: int = 5,
        enabled: bool = True,
    ):
        self.provider = provider
        self.triggers = triggers or dict(DEFAULT_AUTO_IMAGE_TRIGGERS)
        self.cooldown_seconds = cooldown_seconds
        self.max_per_combat = max_per_combat
        self.enabled = enabled

        # Runtime state (not persisted)
        self._last_image_time: float = 0
        self._combat_image_count: int = 0

    def is_enabled(self) -> bool:
        return self.enabled

    def set_enabled(self, enabled: bool) -> None:
        self.enabled = enabled

    def set_triggers(self, triggers: dict[str, bool]) -> None:
        self.triggers = triggers

    def should_generate(self, ctx: ImageContext) -> bool:
        """Fast check — should we even consider generating for this event?"""
        if not self.enabled:
            return False
        if self._is_cooldown_active():
            return False
        return self.triggers.get(ctx.scene_type, self.triggers.get("other", False))

    def _is_cooldown_active(self) -> bool:
        return (time.time() - self._last_image_time) < self.cooldown_seconds

    def _record_image_sent(self) -> None:
        self._last_image_time = time.time()
        self._combat_image_count += 1

    def reset_combat_count(self) -> None:
        self._combat_image_count = 0

    async def maybe_generate(self, ctx: ImageContext) -> ImageResult | None:
        """
        Main entry point. Called after every narrative generation.

        Returns:
            ImageResult if an image was generated and sent
            None if no image was generated (no trigger match, cooldown, etc.)
        """
        if not self.should_generate(ctx):
            return None

        # Check combat image limit
        if ctx.combat_state and self._combat_image_count >= self.max_per_combat:
            return None

        # Build prompt
        prompt = build_scene_prompt(
            narrative=ctx.narrative,
            scene_type=ctx.scene_type,
            genre=ctx.genre,
            characters=ctx.characters,
            mood=ctx.mood,
        )

        # Generate
        try:
            result = await self.provider.generate(
                prompt=prompt,
                scene_type=ctx.scene_type,
            )
        except ImageGenerationError as e:
            # Log but don't crash the narrative flow
            import logging
            logging.warning(f"[ImageEventHandler] Generation failed: {e}")
            return None

        self._record_image_sent()
        return result

    # ── Convenience class methods for common scene types ──────────────────────

    @classmethod
    def from_action_result(
        cls,
        provider: ImageProvider,
        result: Any,
        genre: str = "fantasy",
        **extra_ctx,
    ) -> "ImageEventHandler":
        """
        Build an ImageContext from an ActionRouter result.

        Usage:
            result = router.route(update, action_text)
            ctx = ImageContext.from_action_result(provider, result, genre="fantasy")
            image_result = await handler.maybe_generate(ctx)
        """
        ctx = ImageContext(
            scene_type=cls._infer_scene_type(result),
            narrative=result.narrative,
            genre=genre,
            characters=[],  # Filled by caller
            is_critical=result.nat_20,
            is_fumble=result.nat_1,
            **extra_ctx,
        )
        return ctx

    @staticmethod
    def _infer_scene_type(result: Any) -> str:
        """Infer scene_type from ActionResult fields."""
        if getattr(result, "nat_20", False):
            return "nat_20"
        if getattr(result, "nat_1", False):
            return "nat_1"
        return "other"
