"""
monster_manual.py — D&D 5e Monster Manual lookup tables.

Provides MONSTER_MANUAL dict with 30+ creature stat blocks,
CR_XP mapping, and lookup functions for encounter generation.
Part of Scene Director's content engine suite.

Design: Pure data module — no mutable state, no LLM, O(1) dict lookups.
"""

from __future__ import annotations

from typing import List, Optional

# ── CR to XP reward table (D&D 5e SRD) ────────────────────────────────────
CR_XP: dict[float, int] = {
    0: 10,
    0.125: 25,
    0.25: 50,
    0.5: 100,
    1: 200,
    2: 450,
    3: 700,
    4: 1100,
    5: 1800,
    6: 2300,
    7: 2900,
    8: 3900,
    9: 5000,
    10: 5900,
    11: 7200,
    12: 8400,
    13: 10000,
    14: 11500,
    15: 13000,
    16: 15000,
    17: 18000,
    18: 20000,
    19: 22000,
    20: 25000,
    21: 33000,
    22: 41000,
    23: 50000,
    24: 62000,
    25: 75000,
    26: 90000,
    27: 105000,
    28: 120000,
    29: 135000,
    30: 155000,
}

# ── Monster Manual ────────────────────────────────────────────────────────

# Helper: build a standard monster dict
def _m(
    name: str,
    size: str,
    creature_type: str,
    alignment: str,
    ac: int,
    hp_max: int,
    hp_formula: str,
    speed: int,
    fly_speed: int = 0,
    swim_speed: int = 0,
    climb_speed: int = 0,
    STR: int = 10, DEX: int = 10, CON: int = 10,
    INT: int = 10, WIS: int = 10, CHA: int = 10,
    saving_throws: dict | None = None,
    skills: dict | None = None,
    damage_vulnerabilities: list | None = None,
    damage_resistances: list | None = None,
    damage_immunities: list | None = None,
    condition_immunities: list | None = None,
    senses: str = "",
    senses_passive: int = 10,
    languages: str = "",
    cr: float = 0,
    attacks: list | None = None,
    multiattack: str | None = None,
    legendary_actions: list | None = None,
    lair_actions: list | None = None,
) -> dict:
    spd_parts = [f"{speed} ft."]
    if fly_speed:
        spd_parts.append(f"fly {fly_speed} ft.")
    if swim_speed:
        spd_parts.append(f"swim {swim_speed} ft.")
    if climb_speed:
        spd_parts.append(f"climb {climb_speed} ft.")

    return {
        "name": name,
        "size": size,
        "type": creature_type,
        "alignment": alignment,
        "ac": ac,
        "hp": {"max": hp_max, "formula": hp_formula},
        "speed": ", ".join(spd_parts),
        "STR": STR, "DEX": DEX, "CON": CON,
        "INT": INT, "WIS": WIS, "CHA": CHA,
        "saving_throws": saving_throws or {},
        "skills": skills or {},
        "damage_resistances": damage_resistances or [],
        "damage_immunities": damage_immunities or [],
        "condition_immunities": condition_immunities or [],
        "senses": senses,
        "senses_passive": senses_passive,
        "languages": languages,
        "cr": cr,
        "xp": CR_XP.get(cr, 0),
        "attacks": attacks or [],
        "multiattack": multiattack,
        "legendary_actions": legendary_actions,
        "lair_actions": lair_actions,
    }


MONSTER_MANUAL: dict[str, dict] = {
    # ── CR 0 ──
    "giant_rat": _m("giant_rat", "Small", "beast", "unaligned",
                     12, 7, "2d6", 30,
                     STR=7, DEX=15, CON=11, INT=2, WIS=10, CHA=4,
                     senses="darkvision 60 ft.", senses_passive=10,
                     cr=0,
                     attacks=[{"name": "Bite", "attack_bonus": 4, "damage": "1d4+2",
                               "damage_type": "piercing", "reach": 5}]),

    "giant_bat": _m("giant_bat", "Large", "beast", "unaligned",
                     13, 22, "4d10", 10, fly_speed=60,
                     STR=15, DEX=16, CON=11, INT=2, WIS=12, CHA=6,
                     senses="blindsight 60 ft.", senses_passive=11,
                     cr=0,
                     attacks=[{"name": "Bite", "attack_bonus": 4, "damage": "1d6+2",
                               "damage_type": "piercing", "reach": 5}]),

    # ── CR 0.125 ──
    "kobold": _m("kobold", "Small", "humanoid", "lawful evil",
                  12, 5, "2d6-2", 30,
                  STR=7, DEX=15, CON=9, INT=8, WIS=7, CHA=8,
                  senses="darkvision 60 ft.", senses_passive=8,
                  languages="Common, Draconic",
                  cr=0.125,
                  attacks=[{"name": "Dagger", "attack_bonus": 4, "damage": "1d4+2",
                            "damage_type": "piercing", "reach": 5},
                           {"name": "Sling", "attack_bonus": 4, "damage": "1d4+2",
                            "damage_type": "bludgeoning", "reach": "30/120"}]),

    "bandit": _m("bandit", "Medium", "humanoid", "any non-lawful",
                  12, 11, "2d8+2", 30,
                  STR=11, DEX=12, CON=12, INT=10, WIS=10, CHA=10,
                  senses_passive=10, languages="any one (usually Common)",
                  cr=0.125,
                  attacks=[{"name": "Scimitar", "attack_bonus": 3, "damage": "1d6+1",
                            "damage_type": "slashing", "reach": 5},
                           {"name": "Light Crossbow", "attack_bonus": 3, "damage": "1d8+1",
                            "damage_type": "piercing", "reach": "80/320"}]),

    "cultist": _m("cultist", "Medium", "humanoid", "any non-good",
                   12, 9, "2d8", 30,
                   STR=11, DEX=12, CON=10, INT=10, WIS=11, CHA=10,
                   skills={"Deception": 2, "Religion": 2},
                   senses_passive=10, languages="any one (usually Common)",
                   cr=0.125,
                   attacks=[{"name": "Scimitar", "attack_bonus": 3, "damage": "1d6+1",
                             "damage_type": "slashing", "reach": 5}]),

    # ── CR 0.25 ──
    "goblin": _m("goblin", "Small", "humanoid", "neutral evil",
                  15, 7, "2d6", 30,
                  STR=8, DEX=14, CON=10, INT=10, WIS=8, CHA=8,
                  skills={"Stealth": 6},
                  senses="darkvision 60 ft.", senses_passive=9,
                  languages="Common, Goblin",
                  cr=0.25,
                  attacks=[{"name": "Scimitar", "attack_bonus": 4, "damage": "1d6+2",
                            "damage_type": "slashing", "reach": 5},
                           {"name": "Shortbow", "attack_bonus": 4, "damage": "1d6+2",
                            "damage_type": "piercing", "reach": "80/320"}]),

    "skeleton": _m("skeleton", "Medium", "undead", "lawful evil",
                    13, 13, "2d8+4", 30,
                    STR=10, DEX=14, CON=15, INT=6, WIS=8, CHA=5,
                    damage_vulnerabilities=["bludgeoning"],
                    damage_immunities=["poison"],
                    condition_immunities=["exhaustion", "poisoned"],
                    senses="darkvision 60 ft.", senses_passive=9,
                    languages="understands all languages it knew but cannot speak",
                    cr=0.25,
                    attacks=[{"name": "Shortsword", "attack_bonus": 4, "damage": "1d6+2",
                              "damage_type": "piercing", "reach": 5},
                             {"name": "Shortbow", "attack_bonus": 4, "damage": "1d6+2",
                              "damage_type": "piercing", "reach": "80/320"}]),

    "zombie": _m("zombie", "Medium", "undead", "neutral evil",
                  8, 22, "3d8+9", 20,
                  STR=13, DEX=6, CON=16, INT=3, WIS=6, CHA=5,
                  saving_throws={"WIS": 0},
                  damage_immunities=["poison"],
                  condition_immunities=["poisoned"],
                  senses="darkvision 60 ft.", senses_passive=8,
                  languages="understands all languages it knew but cannot speak",
                  cr=0.25,
                  attacks=[{"name": "Slam", "attack_bonus": 3, "damage": "1d6+1",
                            "damage_type": "bludgeoning", "reach": 5}]),

    # ── CR 0.5 ──
    "orc": _m("orc", "Medium", "humanoid", "chaotic evil",
               13, 15, "2d8+6", 30,
               STR=16, DEX=12, CON=16, INT=7, WIS=11, CHA=10,
               skills={"Intimidation": 2},
               senses="darkvision 60 ft.", senses_passive=10,
               languages="Common, Orc",
               cr=0.5,
               attacks=[{"name": "Greataxe", "attack_bonus": 5, "damage": "1d12+3",
                         "damage_type": "slashing", "reach": 5},
                        {"name": "Javelin", "attack_bonus": 5, "damage": "1d6+3",
                         "damage_type": "piercing", "reach": "30/120"}]),

    "hobgoblin": _m("hobgoblin", "Medium", "humanoid", "lawful evil",
                     18, 11, "2d8+2", 30,
                     STR=13, DEX=12, CON=12, INT=10, WIS=10, CHA=9,
                     senses="darkvision 60 ft.", senses_passive=10,
                     languages="Common, Goblin",
                     cr=0.5,
                     attacks=[{"name": "Longsword", "attack_bonus": 3, "damage": "1d8+1",
                               "damage_type": "slashing", "reach": 5},
                              {"name": "Longbow", "attack_bonus": 3, "damage": "1d8+1",
                               "damage_type": "piercing", "reach": "150/600"}]),

    "gnoll": _m("gnoll", "Medium", "humanoid", "chaotic evil",
                 15, 22, "5d8", 30,
                 STR=14, DEX=12, CON=11, INT=6, WIS=10, CHA=7,
                 senses="darkvision 60 ft.", senses_passive=10,
                 languages="Gnoll",
                 cr=0.5,
                 attacks=[{"name": "Bite", "attack_bonus": 4, "damage": "1d4+2",
                           "damage_type": "piercing", "reach": 5},
                          {"name": "Spear", "attack_bonus": 4, "damage": "1d6+2",
                           "damage_type": "piercing", "reach": 5},
                          {"name": "Longbow", "attack_bonus": 3, "damage": "1d8+1",
                           "damage_type": "piercing", "reach": "150/600"}]),

    "shadow": _m("shadow", "Medium", "undead", "chaotic evil",
                  12, 16, "3d8+3", 40,
                  STR=6, DEX=14, CON=13, INT=6, WIS=10, CHA=8,
                  skills={"Stealth": 4},
                  damage_vulnerabilities=["radiant"],
                  damage_resistances=["acid", "cold", "fire", "lightning", "thunder",
                                      "bludgeoning", "piercing", "slashing from nonmagical weapons"],
                  damage_immunities=["necrotic", "poison"],
                  condition_immunities=["exhaustion", "frightened", "grappled",
                                        "paralyzed", "petrified", "poisoned", "prone", "restrained"],
                  senses="darkvision 60 ft.", senses_passive=10,
                  cr=0.5,
                  attacks=[{"name": "Strength Drain", "attack_bonus": 4, "damage": "2d6+2",
                            "damage_type": "necrotic", "reach": 5}]),

    # ── CR 1 ──
    "bugbear": _m("bugbear", "Medium", "humanoid", "chaotic evil",
                   16, 27, "5d8+5", 30,
                   STR=15, DEX=14, CON=13, INT=8, WIS=11, CHA=9,
                   skills={"Stealth": 6, "Survival": 2},
                   senses="darkvision 60 ft.", senses_passive=10,
                   languages="Common, Goblin",
                   cr=1,
                   attacks=[{"name": "Morningstar", "attack_bonus": 4, "damage": "2d8+2",
                             "damage_type": "piercing", "reach": 5},
                            {"name": "Javelin", "attack_bonus": 4, "damage": "1d6+2",
                             "damage_type": "piercing", "reach": "30/120"}]),

    "ghoul": _m("ghoul", "Medium", "undead", "chaotic evil",
                 12, 22, "5d8", 30,
                 STR=13, DEX=15, CON=10, INT=7, WIS=10, CHA=6,
                 damage_immunities=["poison"],
                 condition_immunities=["charmed", "exhaustion", "poisoned"],
                 senses="darkvision 60 ft.", senses_passive=10,
                 languages="Common",
                 cr=1,
                 attacks=[{"name": "Bite", "attack_bonus": 2, "damage": "2d6+2",
                           "damage_type": "piercing", "reach": 5},
                          {"name": "Claws", "attack_bonus": 4, "damage": "2d4+2",
                           "damage_type": "slashing", "reach": 5}]),

    "specter": _m("specter", "Medium", "undead", "chaotic evil",
                   12, 22, "5d8", 0, fly_speed=50,
                   STR=1, DEX=14, CON=11, INT=10, WIS=10, CHA=11,
                   damage_resistances=["acid", "cold", "fire", "lightning", "thunder",
                                       "bludgeoning", "piercing", "slashing from nonmagical weapons"],
                   damage_immunities=["necrotic", "poison"],
                   condition_immunities=["charmed", "exhaustion", "grappled",
                                         "paralyzed", "petrified", "poisoned", "prone",
                                         "restrained", "unconscious"],
                   senses="darkvision 60 ft.", senses_passive=10,
                   languages="understands all languages it knew but cannot speak",
                   cr=1,
                   attacks=[{"name": "Life Drain", "attack_bonus": 4, "damage": "3d6",
                             "damage_type": "necrotic", "reach": 5}]),

    "giant_spider": _m("giant_spider", "Large", "beast", "unaligned",
                        14, 26, "4d10+4", 30, climb_speed=30,
                        STR=14, DEX=16, CON=12, INT=2, WIS=11, CHA=4,
                        skills={"Stealth": 7},
                        senses="blindsight 10 ft., darkvision 60 ft.", senses_passive=10,
                        cr=1,
                        attacks=[{"name": "Bite", "attack_bonus": 5, "damage": "1d8+3",
                                  "damage_type": "piercing", "reach": 5}]),

    # ── CR 2 ──
    "ogre": _m("ogre", "Large", "giant", "chaotic evil",
                11, 59, "7d10+21", 40,
                STR=19, DEX=8, CON=16, INT=5, WIS=7, CHA=7,
                senses="darkvision 60 ft.", senses_passive=8,
                languages="Common, Giant",
                cr=2,
                attacks=[{"name": "Greatclub", "attack_bonus": 6, "damage": "2d8+4",
                          "damage_type": "bludgeoning", "reach": 5},
                         {"name": "Javelin", "attack_bonus": 6, "damage": "2d6+4",
                          "damage_type": "piercing", "reach": "30/120"}]),

    "minotaur": _m("minotaur", "Large", "monstrosity", "chaotic evil",
                    14, 76, "9d10+27", 40,
                    STR=18, DEX=11, CON=16, INT=6, WIS=16, CHA=9,
                    skills={"Perception": 7},
                    senses="darkvision 60 ft.", senses_passive=17,
                    languages="Abyssal",
                    cr=2,
                    attacks=[{"name": "Greataxe", "attack_bonus": 6, "damage": "2d12+4",
                              "damage_type": "slashing", "reach": 5},
                             {"name": "Gore", "attack_bonus": 6, "damage": "2d8+4",
                              "damage_type": "piercing", "reach": 5}]),

    "gelatinous_cube": _m("gelatinous_cube", "Large", "ooze", "unaligned",
                           6, 84, "8d10+40", 15,
                           STR=14, DEX=3, CON=20, INT=1, WIS=6, CHA=1,
                           condition_immunities=["blinded", "charmed", "deafened",
                                                  "exhaustion", "frightened", "prone"],
                           senses="blindsight 60 ft.", senses_passive=8,
                           cr=2,
                           attacks=[{"name": "Pseudopod", "attack_bonus": 4, "damage": "3d6",
                                     "damage_type": "acid", "reach": 5}]),

    # ── CR 3 ──
    "werewolf": _m("werewolf", "Medium", "humanoid", "chaotic evil",
                    11, 58, "9d8+18", 30,
                    STR=15, DEX=13, CON=14, INT=10, WIS=11, CHA=10,
                    skills={"Perception": 4},
                    damage_immunities=["bludgeoning", "piercing",
                                       "slashing from nonmagical non-silvered weapons"],
                    senses_passive=14, languages="Common",
                    cr=3,
                    attacks=[{"name": "Multiattack", "attack_bonus": 0, "damage": "0",
                              "damage_type": "special", "reach": 0},
                             {"name": "Bite (wolf form)", "attack_bonus": 4, "damage": "1d8+2",
                              "damage_type": "piercing", "reach": 5},
                             {"name": "Claws (hybrid form)", "attack_bonus": 4, "damage": "2d4+2",
                              "damage_type": "slashing", "reach": 5}],
                    multiattack="The werewolf makes two attacks: one with its bite and one with its claws."),

    "owlbear": _m("owlbear", "Large", "monstrosity", "unaligned",
                   13, 59, "7d10+21", 40,
                   STR=20, DEX=12, CON=17, INT=3, WIS=12, CHA=7,
                   skills={"Perception": 3},
                   senses="darkvision 60 ft.", senses_passive=13,
                   cr=3,
                   attacks=[{"name": "Multiattack", "attack_bonus": 0, "damage": "0",
                             "damage_type": "special", "reach": 0},
                            {"name": "Beak", "attack_bonus": 7, "damage": "1d10+5",
                              "damage_type": "piercing", "reach": 5},
                            {"name": "Claws", "attack_bonus": 7, "damage": "2d8+5",
                              "damage_type": "slashing", "reach": 5}],
                   multiattack="The owlbear makes two attacks: one with its beak and one with its claws."),

    "displacer_beast": _m("displacer_beast", "Large", "monstrosity", "lawful evil",
                           13, 85, "10d10+30", 40,
                           STR=18, DEX=15, CON=16, INT=6, WIS=12, CHA=8,
                           senses="darkvision 60 ft.", senses_passive=11,
                           cr=3,
                           attacks=[{"name": "Multiattack", "attack_bonus": 0, "damage": "0",
                                     "damage_type": "special", "reach": 0},
                                    {"name": "Tentacle", "attack_bonus": 6, "damage": "1d6+4",
                                      "damage_type": "bludgeoning", "reach": 10},
                                    {"name": "Tentacle (2nd)", "attack_bonus": 6, "damage": "1d6+4",
                                      "damage_type": "bludgeoning", "reach": 10}],
                           multiattack="The displacer beast makes two attacks with its tentacles."),

    "wight": _m("wight", "Medium", "undead", "neutral evil",
                 14, 45, "6d8+18", 30,
                 STR=15, DEX=14, CON=16, INT=10, WIS=13, CHA=15,
                 skills={"Perception": 3, "Stealth": 4},
                 damage_resistances=["necrotic", "bludgeoning", "piercing",
                                     "slashing from nonmagical non-silvered weapons"],
                 damage_immunities=["poison"],
                 condition_immunities=["exhaustion", "poisoned"],
                 senses="darkvision 60 ft.", senses_passive=13,
                 languages="the languages it knew in life",
                 cr=3,
                 attacks=[{"name": "Multiattack", "attack_bonus": 0, "damage": "0",
                           "damage_type": "special", "reach": 0},
                          {"name": "Longsword", "attack_bonus": 4, "damage": "1d8+2",
                            "damage_type": "slashing", "reach": 5},
                          {"name": "Life Drain", "attack_bonus": 4, "damage": "1d6+2",
                            "damage_type": "necrotic", "reach": 5}],
                 multiattack="The wight makes two longsword attacks or two longbow attacks."),

    "phase_spider": _m("phase_spider", "Large", "monstrosity", "unaligned",
                        13, 32, "5d10+5", 30, climb_speed=30,
                        STR=15, DEX=15, CON=12, INT=6, WIS=10, CHA=6,
                        skills={"Stealth": 6},
                        senses="darkvision 60 ft.", senses_passive=10,
                        cr=3,
                        attacks=[{"name": "Bite", "attack_bonus": 4, "damage": "1d10+2",
                                  "damage_type": "piercing", "reach": 5}]),

    "hell_hound": _m("hell_hound", "Medium", "fiend", "lawful evil",
                      15, 45, "7d8+14", 50,
                      STR=17, DEX=12, CON=14, INT=6, WIS=13, CHA=6,
                      skills={"Perception": 5},
                      damage_immunities=["fire"],
                      senses="darkvision 60 ft.", senses_passive=15,
                      languages="understands Infernal but cannot speak",
                      cr=3,
                      attacks=[{"name": "Bite", "attack_bonus": 5, "damage": "1d8+3",
                                "damage_type": "piercing", "reach": 5},
                               {"name": "Fire Breath", "attack_bonus": 0, "damage": "6d6",
                                "damage_type": "fire", "reach": "15 ft. cone", "recharge": "5-6"}]),

    # ── CR 4 ──
    "ghost": _m("ghost", "Medium", "undead", "any alignment",
                 11, 45, "10d8", 0, fly_speed=40,
                 STR=7, DEX=13, CON=10, INT=10, WIS=12, CHA=17,
                 damage_resistances=["acid", "fire", "lightning", "thunder",
                                     "bludgeoning", "piercing", "slashing from nonmagical weapons"],
                 damage_immunities=["cold", "necrotic", "poison"],
                 condition_immunities=["charmed", "exhaustion", "frightened",
                                       "grappled", "paralyzed", "petrified",
                                       "poisoned", "prone", "restrained"],
                 senses="darkvision 60 ft.", senses_passive=11,
                 languages="any languages it knew in life",
                 cr=4,
                 attacks=[{"name": "Withering Touch", "attack_bonus": 5, "damage": "4d6+3",
                           "damage_type": "necrotic", "reach": 5},
                          {"name": "Possession", "attack_bonus": 0, "damage": "0",
                           "damage_type": "special", "reach": 5, "recharge": "6"}]),


    # ── CR 5 ──
    "troll": _m("troll", "Large", "giant", "chaotic evil",
                 15, 84, "8d10+40", 30,
                 STR=18, DEX=13, CON=20, INT=7, WIS=9, CHA=7,
                 skills={"Perception": 2},
                 senses="darkvision 60 ft.", senses_passive=12,
                 languages="Giant",
                 cr=5,
                 attacks=[{"name": "Multiattack", "attack_bonus": 0, "damage": "0",
                           "damage_type": "special", "reach": 0},
                          {"name": "Bite", "attack_bonus": 7, "damage": "1d6+4",
                            "damage_type": "piercing", "reach": 5},
                          {"name": "Claw", "attack_bonus": 7, "damage": "2d6+4",
                            "damage_type": "slashing", "reach": 5},
                          {"name": "Claw (2nd)", "attack_bonus": 7, "damage": "2d6+4",
                            "damage_type": "slashing", "reach": 5}],
                 multiattack="The troll makes three attacks: one with its bite and two with its claws."),

    "vampire_spawn": _m("vampire_spawn", "Medium", "undead", "neutral evil",
                         15, 82, "11d8+33", 30,
                         STR=16, DEX=16, CON=16, INT=11, WIS=10, CHA=12,
                         saving_throws={"DEX": 6, "WIS": 3},
                         skills={"Perception": 3, "Stealth": 6},
                         damage_resistances=["necrotic", "bludgeoning", "piercing",
                                             "slashing from nonmagical weapons"],
                         senses="darkvision 60 ft.", senses_passive=13,
                         languages="the languages it knew in life",
                         cr=5,
                         attacks=[{"name": "Multiattack", "attack_bonus": 0, "damage": "0",
                                   "damage_type": "special", "reach": 0},
                                  {"name": "Claws", "attack_bonus": 6, "damage": "2d4+3",
                                    "damage_type": "slashing", "reach": 5},
                                  {"name": "Bite", "attack_bonus": 6, "damage": "1d6+3",
                                    "damage_type": "piercing", "reach": 5}],
                         multiattack="The vampire spawn makes two attacks: one with its claws and one bit its bite."),

    # ── CR 6 ──
    "wyvern": _m("wyvern", "Large", "dragon", "unaligned",
                  13, 110, "13d10+39", 20, fly_speed=80,
                  STR=19, DEX=10, CON=16, INT=5, WIS=12, CHA=6,
                  skills={"Perception": 4},
                  senses="darkvision 60 ft.", senses_passive=14,
                  cr=6,
                  attacks=[{"name": "Multiattack", "attack_bonus": 0, "damage": "0",
                            "damage_type": "special", "reach": 0},
                           {"name": "Bite", "attack_bonus": 7, "damage": "2d6+4",
                             "damage_type": "piercing", "reach": 10},
                           {"name": "Stinger", "attack_bonus": 7, "damage": "2d6+4",
                             "damage_type": "piercing", "reach": 10}],
                  multiattack="The wyvern makes two attacks: one with its bite and one with its stinger."),

    "mummy": _m("mummy", "Medium", "undead", "lawful evil",
                 11, 58, "9d8+18", 20,
                 STR=16, DEX=8, CON=15, INT=6, WIS=14, CHA=12,
                 saving_throws={"WIS": 5},
                 damage_vulnerabilities=["fire"],
                 damage_resistances=["bludgeoning", "piercing",
                                     "slashing from nonmagical weapons"],
                 damage_immunities=["necrotic", "poison"],
                 condition_immunities=["charmed", "exhaustion", "frightened",
                                       "paralyzed", "poisoned"],
                 senses="darkvision 60 ft.", senses_passive=12,
                 languages="any languages it knew in life",
                 cr=6,
                 attacks=[{"name": "Multiattack", "attack_bonus": 0, "damage": "0",
                           "damage_type": "special", "reach": 0},
                          {"name": "Rotting Fist", "attack_bonus": 5, "damage": "2d6+3",
                            "damage_type": "bludgeoning", "reach": 5}],
                 multiattack="The mummy can use Dreadful Glare and makes one attack with its rotting fist."),

    "chimera": _m("chimera", "Large", "monstrosity", "chaotic evil",
                   14, 114, "12d10+48", 30, fly_speed=60,
                   STR=19, DEX=11, CON=19, INT=3, WIS=14, CHA=10,
                   skills={"Perception": 8},
                   senses="darkvision 60 ft.", senses_passive=18,
                   languages="understands Draconic but cannot speak",
                   cr=6,
                   attacks=[{"name": "Multiattack", "attack_bonus": 0, "damage": "0",
                             "damage_type": "special", "reach": 0},
                            {"name": "Bite", "attack_bonus": 7, "damage": "2d6+4",
                              "damage_type": "piercing", "reach": 5},
                            {"name": "Claws", "attack_bonus": 7, "damage": "2d6+4",
                              "damage_type": "slashing", "reach": 5},
                            {"name": "Horns", "attack_bonus": 7, "damage": "1d12+4",
                              "damage_type": "bludgeoning", "reach": 5},
                            {"name": "Fire Breath", "attack_bonus": 0, "damage": "7d8",
                              "damage_type": "fire", "reach": "15 ft. cone", "recharge": "5-6"}],
                   multiattack="The chimera makes three attacks: one with its bite, one with its horns, and one with its claws."),

    # ── CR 10 ──
    "stone_golem": _m("stone_golem", "Large", "construct", "unaligned",
                       17, 178, "17d10+85", 30,
                       STR=22, DEX=9, CON=20, INT=3, WIS=11, CHA=1,
                       damage_immunities=["poison", "psychic",
                                          "bludgeoning", "piercing", "slashing from nonmagical non-adamantine weapons"],
                       condition_immunities=["charmed", "exhaustion", "frightened",
                                             "paralyzed", "petrified", "poisoned"],
                       senses="darkvision 120 ft.", senses_passive=10,
                       languages="understands the languages of its creator but cannot speak",
                       cr=10,
                       attacks=[{"name": "Multiattack", "attack_bonus": 0, "damage": "0",
                                 "damage_type": "special", "reach": 0},
                                {"name": "Slam", "attack_bonus": 10, "damage": "3d8+6",
                                  "damage_type": "bludgeoning", "reach": 5},
                                {"name": "Slam (2nd)", "attack_bonus": 10, "damage": "3d8+6",
                                  "damage_type": "bludgeoning", "reach": 5}],
                       multiattack="The golem makes two slam attacks."),

    "young_red_dragon": _m("young_red_dragon", "Large", "dragon", "chaotic evil",
                            18, 178, "17d10+85", 40, fly_speed=80, climb_speed=40,
                            STR=23, DEX=10, CON=21, INT=14, WIS=11, CHA=19,
                            saving_throws={"DEX": 4, "CON": 9, "WIS": 4, "CHA": 8},
                            skills={"Perception": 8, "Stealth": 4},
                            damage_immunities=["fire"],
                            senses="blindsight 30 ft., darkvision 120 ft.", senses_passive=18,
                            languages="Common, Draconic",
                            cr=10,
                            attacks=[{"name": "Multiattack", "attack_bonus": 0, "damage": "0",
                                      "damage_type": "special", "reach": 0},
                                     {"name": "Bite", "attack_bonus": 10, "damage": "2d10+6",
                                       "damage_type": "piercing", "reach": 10},
                                     {"name": "Claw", "attack_bonus": 10, "damage": "2d6+6",
                                       "damage_type": "slashing", "reach": 5},
                                     {"name": "Claw (2nd)", "attack_bonus": 10, "damage": "2d6+6",
                                       "damage_type": "slashing", "reach": 5},
                                     {"name": "Fire Breath", "attack_bonus": 0, "damage": "16d6",
                                       "damage_type": "fire", "reach": "30 ft. cone", "recharge": "5-6"}],
                            multiattack="The dragon makes three attacks: one with its bite and two with its claws."),

    # ── CR 13 ──
    "adult_white_dragon": _m("adult_white_dragon", "Huge", "dragon", "chaotic evil",
                              18, 200, "16d12+96", 40, fly_speed=80, swim_speed=40,
                              STR=22, DEX=10, CON=22, INT=8, WIS=12, CHA=12,
                              saving_throws={"DEX": 5, "CON": 11, "WIS": 6, "CHA": 6},
                              skills={"Perception": 11, "Stealth": 5},
                              damage_immunities=["cold"],
                              senses="blindsight 60 ft., darkvision 120 ft.", senses_passive=21,
                              languages="Common, Draconic",
                              cr=13,
                              attacks=[{"name": "Multiattack", "attack_bonus": 0, "damage": "0",
                                        "damage_type": "special", "reach": 0},
                                       {"name": "Bite", "attack_bonus": 11, "damage": "2d10+6",
                                         "damage_type": "piercing", "reach": 10},
                                       {"name": "Claw", "attack_bonus": 11, "damage": "2d6+6",
                                         "damage_type": "slashing", "reach": 5},
                                       {"name": "Claw (2nd)", "attack_bonus": 11, "damage": "2d6+6",
                                         "damage_type": "slashing", "reach": 5},
                                       {"name": "Cold Breath", "attack_bonus": 0, "damage": "12d8",
                                         "damage_type": "cold", "reach": "60 ft. cone", "recharge": "5-6"}],
                              multiattack="The dragon makes three attacks: one with its bite and two with its claws.",
                              legendary_actions=[
                                  {"name": "Detect", "description": "The dragon makes a Wisdom (Perception) check."},
                                  {"name": "Tail Attack", "description": "The dragon makes a tail attack (2d8+6 bludgeoning)."},
                                  {"name": "Wing Attack (Costs 2 actions)", "description": "The dragon beats its wings. DC 19 DEX save or 2d6+6 bludgeoning + knocked prone."},
                              ],
                              lair_actions=[
                                  "Freezing fog fills a 20-foot-radius sphere.",
                                  "Jagged ice shards erupt from the ground.",
                              ]),

    # ── CR 21 ──
    "lich": _m("lich", "Medium", "undead", "any evil",
                17, 135, "18d8+54", 30,
                STR=11, DEX=16, CON=16, INT=20, WIS=14, CHA=16,
                saving_throws={"CON": 10, "INT": 12, "WIS": 9},
                skills={"Arcana": 19, "History": 12, "Insight": 9, "Perception": 9},
                damage_resistances=["cold", "lightning", "necrotic"],
                damage_immunities=["poison", "bludgeoning", "piercing",
                                   "slashing from nonmagical weapons"],
                condition_immunities=["charmed", "exhaustion", "frightened",
                                      "paralyzed", "poisoned"],
                senses="truesight 120 ft.", senses_passive=19,
                languages="Common plus up to five other languages",
                cr=21,
                attacks=[{"name": "Paralyzing Touch", "attack_bonus": 12, "damage": "3d6",
                          "damage_type": "cold", "reach": 5},
                         {"name": "Disrupt Life", "attack_bonus": 0, "damage": "10d6",
                          "damage_type": "necrotic", "reach": "20 ft. radius", "recharge": "5-6"}],
                legendary_actions=[
                    {"name": "Cantrip", "description": "The lich casts a cantrip."},
                    {"name": "Paralyzing Touch (Costs 2 actions)", "description": "The lich uses Paralyzing Touch."},
                    {"name": "Frightening Gaze (Costs 2 actions)", "description": "The lich targets a creature within 60 ft. DC 18 WIS save or frightened for 1 minute."},
                ],
                lair_actions=[
                    "The lich rolls a d8 on the spell table and casts a random cantrip.",
                    "Spirits of the dead rise as shadowy forms, dealing 3d6 necrotic damage.",
                ]),

    "ancient_black_dragon": _m("ancient_black_dragon", "Gargantuan", "dragon", "chaotic evil",
                                22, 367, "21d20+147", 40, fly_speed=80, swim_speed=40,
                                STR=27, DEX=14, CON=25, INT=16, WIS=15, CHA=19,
                                saving_throws={"DEX": 9, "CON": 14, "WIS": 9, "CHA": 11},
                                skills={"Perception": 16, "Stealth": 9},
                                damage_immunities=["acid"],
                                senses="blindsight 60 ft., darkvision 120 ft.", senses_passive=26,
                                languages="Common, Draconic",
                                cr=21,
                                attacks=[{"name": "Multiattack", "attack_bonus": 0, "damage": "0",
                                          "damage_type": "special", "reach": 0},
                                         {"name": "Bite", "attack_bonus": 15, "damage": "2d10+8",
                                           "damage_type": "piercing", "reach": 15},
                                         {"name": "Claw", "attack_bonus": 15, "damage": "2d6+8",
                                           "damage_type": "slashing", "reach": 10},
                                         {"name": "Claw (2nd)", "attack_bonus": 15, "damage": "2d6+8",
                                           "damage_type": "slashing", "reach": 10},
                                         {"name": "Tail", "attack_bonus": 15, "damage": "2d8+8",
                                           "damage_type": "bludgeoning", "reach": 20},
                                         {"name": "Acid Breath", "attack_bonus": 0, "damage": "15d8",
                                           "damage_type": "acid", "reach": "90 ft. line", "recharge": "5-6"}],
                                multiattack="The dragon can use its Frightful Presence. It then makes three attacks: one with its bite and two with its claws.",
                                legendary_actions=[
                                    {"name": "Detect", "description": "The dragon makes a Wisdom (Perception) check."},
                                    {"name": "Tail Attack", "description": "The dragon makes a tail attack."},
                                    {"name": "Wing Attack (Costs 2 actions)", "description": "The dragon beats its wings. DC 23 DEX save or 2d6+8 bludgeoning + knocked prone."},
                                ],
                                lair_actions=[
                                    "Pools of acid bubble up dealing 3d6 acid damage.",
                                    "A cloud of biting insects swarms a 20-foot-radius sphere.",
                                ]),
}

# ── Lookup Functions ──────────────────────────────────────────────────────

def get_monster(name: str) -> Optional[dict]:
    """Look up a monster by exact name key.

    Args:
        name: Monster key name (lowercase, snake_case), e.g. "goblin", "young_red_dragon"

    Returns:
        Monster stat block dict, or None if not found.
    """
    return MONSTER_MANUAL.get(name)


def get_monsters_by_cr(min_cr: float, max_cr: float) -> List[str]:
    """Return monster names whose CR falls within [min_cr, max_cr] inclusive.

    Args:
        min_cr: Minimum challenge rating (inclusive)
        max_cr: Maximum challenge rating (inclusive)

    Returns:
        List of monster name strings sorted alphabetically.
    """
    result = [
        name for name, monster in MONSTER_MANUAL.items()
        if min_cr <= monster["cr"] <= max_cr
    ]
    result.sort()
    return result
