#!/usr/bin/env python3
"""
HermesDM Web Companion Setup Helper
Called by install.py when --with-web is passed.

Handles:
  - Install web dependencies (FastAPI, uvicorn, etc.)
  - Write web/.env with auto-detected paths
  - Create launcher script in ~/.local/bin/ (or venv bin/)
  - Port availability check
  - Idempotent re-runs
"""

import os
import shutil
import socket
import subprocess
import sys
from pathlib import Path

DEFAULT_WEB_PORT = 8080
DEFAULT_STATE_DIR = Path.home() / ".hermes" / "hermesdm" / "campaigns"
LAUNCHER_TEMPLATE = """#!/bin/bash
# HermesDM Web Companion Launcher
# Auto-generated by scripts/setup_web.py

set -e

WEB_DIR="{web_dir}"
STATE_DIR="{state_dir}"
PORT="{port}"
VENV_PYTHON="{venv_python}"

cd "$WEB_DIR"

export HERMESDM_STATE_DIR="$STATE_DIR"
export HOST="0.0.0.0"
export PORT="$PORT"

echo "🌐 HermesDM Web Companion"
echo "   State:  $STATE_DIR"
echo "   URL:    http://localhost:$PORT"
echo "   Press Ctrl+C to stop"
echo ""

"$VENV_PYTHON" -m uvicorn server:app --host "$HOST" --port "$PORT" --reload
"""


def find_venv_python(hermesdm_path: Path) -> str:
    """Find the Python interpreter to use (venv preferred)."""
    # Check for venv inside hermesdm repo
    for venv_name in (".venv", "venv"):
        venv_bin = hermesdm_path / venv_name / "bin" / "python"
        if venv_bin.exists():
            return str(venv_bin)
    # Check for hermes-agent venv
    ha_venv = Path.home() / ".hermes" / ".venv" / "bin" / "python"
    if ha_venv.exists():
        return str(ha_venv)
    # Fallback to current Python
    return sys.executable


def install_dependencies(requirements_path: Path, python: str, dry_run: bool = False) -> bool:
    """Install web companion Python dependencies."""
    if dry_run:
        print(f"  [DRY] Would install deps from {requirements_path}")
        return True
    if not requirements_path.exists():
        print(f"  [WARN] requirements.txt not found: {requirements_path}")
        return False
    # Quick check: are deps already available?
    required = ["fastapi", "uvicorn", "sse_starlette", "dotenv"]
    import importlib.util
    missing = [m for m in required if importlib.util.find_spec(m) is None]
    if not missing:
        print("  [OK]  Web dependencies already installed")
        return True
    print(f"  [PIP] Installing web dependencies (missing: {', '.join(missing)})...")
    # Try venv pip first, fallback to system pip
    pip_cmds = [
        [python, "-m", "pip", "install", "-q", "-r", str(requirements_path)],
        ["python3", "-m", "pip", "install", "-q", "-r", str(requirements_path)],
        ["pip3", "install", "-q", "-r", str(requirements_path)],
    ]
    for cmd in pip_cmds:
        try:
            subprocess.run(cmd, check=True, capture_output=True)
            print("  [OK]  Dependencies installed")
            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            continue
    print("  [ERR] pip install failed — try manually: pip3 install -r web/requirements.txt")
    return False


def write_web_env(web_dir: Path, state_dir: str, port: int, dry_run: bool = False) -> None:
    """Write web/.env with correct paths."""
    env_path = web_dir / ".env"
    content = f"""# HermesDM Web Companion — auto-generated by install.py
HERMESDM_STATE_DIR={state_dir}
HOST=0.0.0.0
PORT={port}
"""
    if dry_run:
        print(f"  [DRY] Would write {env_path}")
        return
    env_path.write_text(content)
    print(f"  [OK]  Wrote {env_path}")


def create_launcher(web_dir: Path, state_dir: str, port: int, python: str,
                    dry_run: bool = False) -> Path | None:
    """Create hermesdm-web launcher in ~/.local/bin or venv bin."""
    launcher_dir = Path.home() / ".local" / "bin"
    launcher_dir.mkdir(parents=True, exist_ok=True)
    launcher_path = launcher_dir / "hermesdm-web"

    script = LAUNCHER_TEMPLATE.format(
        web_dir=str(web_dir.resolve()),
        state_dir=state_dir,
        port=port,
        venv_python=python,
    )

    if dry_run:
        print(f"  [DRY] Would create launcher: {launcher_path}")
        return None

    launcher_path.write_text(script)
    launcher_path.chmod(0o755)
    print(f"  [OK]  Created launcher: {launcher_path}")

    # Warn if ~/.local/bin is not in PATH
    if str(launcher_dir) not in os.environ.get("PATH", ""):
        print(f"  [WARN] {launcher_dir} is not in your PATH.")
        print(f"         Add this to your ~/.bashrc or ~/.zshrc:")
        print(f"         export PATH=\"$HOME/.local/bin:$PATH\"")

    return launcher_path


def port_available(port: int) -> bool:
    """Check if a TCP port is available."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        try:
            s.bind(("0.0.0.0", port))
            return True
        except OSError:
            return False


def setup_web(hermesdm_path: Path, state_dir: str | None = None,
              port: int | None = None, dry_run: bool = False) -> bool:
    """Main entry point called by install.py."""
    web_dir = hermesdm_path / "web"
    if not web_dir.exists():
        print(f"  [ERR] Web directory not found: {web_dir}")
        return False

    # Resolve paths
    resolved_state = state_dir or str(DEFAULT_STATE_DIR.expanduser().resolve())
    resolved_port = port or DEFAULT_WEB_PORT

    # Port check
    if not port_available(resolved_port):
        print(f"  [WARN] Port {resolved_port} is already in use.")
        # Try to find an alternative
        for alt in range(resolved_port + 1, resolved_port + 20):
            if port_available(alt):
                print(f"  [INFO] Alternative port available: {alt}")
                if not dry_run:
                    print(f"  [HINT] Re-run with --web-port {alt}")
                return False
        print(f"  [ERR] No free port found between {resolved_port} and {resolved_port + 19}")
        return False

    print(f"\n[WEB] Setting up web companion...")
    print(f"  State dir: {resolved_state}")
    print(f"  Port:      {resolved_port}")

    python = find_venv_python(hermesdm_path)
    print(f"  Python:    {python}")

    ok = True

    # 1. Dependencies
    if not install_dependencies(web_dir / "requirements.txt", python, dry_run):
        ok = False

    # 2. .env
    write_web_env(web_dir, resolved_state, resolved_port, dry_run)

    # 3. Launcher
    launcher = create_launcher(web_dir, resolved_state, resolved_port, python, dry_run)

    if ok and not dry_run:
        print("\n  ✓ Web companion configured!")
        print(f"  Run: hermesdm-web")
        print(f"  Or:  cd {web_dir} && docker compose up -d")
    return ok


def verify_web(hermesdm_path: Path) -> bool:
    """Check if web companion is installed and configured."""
    web_dir = hermesdm_path / "web"
    env_path = web_dir / ".env"
    launcher = Path.home() / ".local" / "bin" / "hermesdm-web"

    checks = [
        ("web/ directory", web_dir.exists()),
        ("web/.env", env_path.exists()),
        ("web/server.py", (web_dir / "server.py").exists()),
        ("web/static/index.html", (web_dir / "static" / "index.html").exists()),
        ("launcher hermesdm-web", launcher.exists()),
    ]

    all_ok = True
    for name, ok in checks:
        status = "✓" if ok else "✗"
        print(f"    {status} {name}")
        if not ok:
            all_ok = False
    return all_ok


def uninstall_web(hermesdm_path: Path, dry_run: bool = False) -> bool:
    """Remove web companion configuration."""
    web_dir = hermesdm_path / "web"
    env_path = web_dir / ".env"
    launcher = Path.home() / ".local" / "bin" / "hermesdm-web"

    removed_any = False
    for path, name in [(env_path, ".env"), (launcher, "launcher")]:
        if path.exists():
            if dry_run:
                print(f"  [DRY] Would remove {name}: {path}")
            else:
                path.unlink()
                print(f"  [OK]  Removed {name}: {path}")
                removed_any = True
    if not removed_any:
        print("  [INFO] Nothing to remove — web companion not configured")
    return True


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--hermesdm-path", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--state-dir", type=str, default=None)
    parser.add_argument("--port", type=int, default=None)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--verify", action="store_true")
    parser.add_argument("--uninstall", action="store_true")
    args = parser.parse_args()

    if args.verify:
        print("=== Web Companion Status ===")
        ok = verify_web(args.hermesdm_path)
        sys.exit(0 if ok else 1)
    elif args.uninstall:
        print("=== Uninstalling Web Companion ===")
        uninstall_web(args.hermesdm_path, args.dry_run)
        sys.exit(0)
    else:
        ok = setup_web(args.hermesdm_path, args.state_dir, args.port, args.dry_run)
        sys.exit(0 if ok else 1)
